from abc import ABC, abstractmethod
from typing import Iterator, Iterable, Tuple
import numpy as np

class IVAD(ABC):
    @abstractmethod
    def is_speech(self, audio_chunk: np.ndarray) -> bool:
        """Determines if the given audio chunk contains speech."""
        pass

class IASR(ABC):
    @abstractmethod
    def transcribe(self, audio_array: np.ndarray) -> str:
        """Transcribes the given audio array into text."""
        pass

class ITTS(ABC):
    @abstractmethod
    def synthesize(self, text: str) -> Tuple[np.ndarray, int]:
        """
        Synthesizes text into audio.
        Returns a tuple of (audio_array, sample_rate).
        """
        pass

class ILLM(ABC):
    @abstractmethod
    def generate_response_stream(self, text: str) -> Iterable[str]:
        """
        Takes user text and yields strings (tokens or chunks of text)
        as they are generated by the LLM.
        """
        pass

    @abstractmethod
    def add_human_message(self, text: str) -> None:
        """Adds a human message to the LLM's conversational memory."""
        pass

    @abstractmethod
    def add_ai_message(self, text: str) -> None:
        """Adds an AI message to the LLM's conversational memory."""
        pass

    @property
    @abstractmethod
    def active_agent_name(self) -> str:
        """Returns the name of the currently active agent."""
        pass
